# Generated by Django 4.0.4 on 2022-10-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='last_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='house_number',
            field=models.CharField(max_length=5),
        ),
    ]
