# Generated by Django 4.0.4 on 2022-10-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_anonymoususer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
