# Generated by Django 4.0.4 on 2022-10-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_anonymoususer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
