# Generated by Django 4.0.4 on 2022-12-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_anonymoususer_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='name',
            new_name='first_name',
        ),
    ]
