# Generated by Django 4.0.4 on 2022-12-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0009_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
