# Generated by Django 4.0.4 on 2022-10-14 09:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_anonymoususer_last_name_and_more'),
        ('seller', '0002_orderpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyer_anon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.anonymoususer')),
                ('item_to_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.item')),
                ('order_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.orderpackage')),
            ],
        ),
    ]
