# Generated by Django 4.0.4 on 2022-10-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_basket_basketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='order_package',
            new_name='order',
        ),
    ]
