# Generated by Django 4.0.4 on 2022-09-06 13:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(default='0.00', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price in €')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('CO', 'Cookies'), ('CA', 'Cakes'), ('I', 'Ice creams'), ('ALL', 'All Sweets')], default='ALL', max_length=3)),
                ('image', models.ImageField(upload_to='product_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
