# Generated by Django 4.0.4 on 2022-10-20 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_anonymoususer_last_name_and_more'),
        ('store', '0001_initial'),
        ('seller', '0002_orderpackage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPackage',
            new_name='Order',
        ),
    ]
