# Generated by Django 4.0.4 on 2022-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_orderpackage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
